/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package goitpackage;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class App {

    public static void main(String[] args) {

        Person person = new Person("Iryna", "Shurda");

        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String json = gson.toJson(person);
        System.out.println(json);
    }
}
